<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ $name }} - Bio Page</title>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <style>
        :root {
            --primary-color:
                {{ $color }}
            ;
            --bg-color:
                {{ $bg_color }}
            ;
        }

        body {
            font-family: 'Inter', sans-serif;
            background-color: var(--bg-color);
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
            margin: 0;
            padding: 20px;
        }

        .bio-card {
            background: white;
            width: 100%;
            max-width: 400px;
            padding: 40px 30px;
            border-radius: 20px;
            box-shadow: 0 10px 30px rgba(0, 0, 0, 0.1);
            text-align: center;
            border-top: 5px solid var(--primary-color);
        }

        h1 {
            margin-bottom: 30px;
            color: #2D3436;
            font-size: 1.8rem;
        }

        .bio-link-btn {
            display: flex;
            align-items: center;
            justify-content: center;
            gap: 10px;
            width: 100%;
            padding: 15px;
            margin-bottom: 15px;
            background: white;
            border: 2px solid #DFE6E9;
            border-radius: 12px;
            text-decoration: none;
            color: #2D3436;
            font-weight: 600;
            transition: all 0.3s ease;
        }

        .bio-link-btn:hover {
            border-color: var(--primary-color);
            color: var(--primary-color);
            transform: translateY(-3px);
            box-shadow: 0 5px 15px rgba(0, 0, 0, 0.05);
        }

        .bio-link-btn i {
            font-size: 1.2rem;
        }

        .footer {
            margin-top: 30px;
            font-size: 0.8rem;
            color: #B2BEC3;
        }
    </style>
</head>

<body>
    <div class="bio-card">
        <h1>{{ $name }}</h1>
        <div class="links-container">
            @foreach($links as $link)
                @php
                    $platformKey = $link['platform'] ?? 'website';
                    $platformData = $platforms[$platformKey] ?? $platforms['website'] ?? null;

                    $label = !empty($link['label']) ? $link['label'] : ($platformData ? $platformData->label : ucfirst($platformKey));
                    $iconClass = $platformData ? $platformData->icon : 'fa-solid fa-globe';
                @endphp
                <a href="{{ $link['url'] }}" target="_blank" class="bio-link-btn">
                    <i class="{{ $iconClass }}"></i> {{ $label }}
                </a>
            @endforeach
        </div>
        <div class="footer">
            Generated by Free QR Generator
        </div>
    </div>
</body>

</html>